apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: brupop-apiserver-certificate
  namespace: {{ .Values.namespace }}
spec:
  isCA: true
  commonName: my-selfsigned-ca
  secretName: brupop-tls
  privateKey:
    algorithm: RSA
    encoding: PKCS8
  dnsNames:
    - brupop-apiserver.brupop-bottlerocket-aws.svc.cluster.local
    - brupop-apiserver.brupop-bottlerocket-aws.svc
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
