{{- if .Values.rbacapiserver.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: apiserver
    app.kubernetes.io/managed-by: brupop
    app.kubernetes.io/part-of: brupop
    brupop.bottlerocket.aws/component: apiserver
  name: {{ .Values.rbacapiserver.name}}-role
 #namespace: brupop-bottlerocket-aws
rules:
  - apiGroups:
      - brupop.bottlerocket.aws
    resources:
      - bottlerocketshadows
      - bottlerocketshadows/status
    verbs:
      - create
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - watch
      - update
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - patch
  - apiGroups:
      - ""
    resources:
      - pods/eviction
    verbs:
      - create
{{- end -}}
