{{- if .Values.rbaccontroller.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: brupop-controller
    app.kubernetes.io/managed-by: brupop
    app.kubernetes.io/part-of: brupop
    brupop.bottlerocket.aws/component: brupop-controller
  name: {{ .Values.rbaccontroller.name }}
  #namespace: brupop-bottlerocket-aws
rules:
  - apiGroups:
      - brupop.bottlerocket.aws
    resources:
      - bottlerocketshadows
      - bottlerocketshadows/status
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - brupop.bottlerocket.aws
    resources:
      - bottlerocketshadows
    verbs:
      - create
      - patch
      - update
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
{{- end -}}
