apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/component: agent
    app.kubernetes.io/managed-by: brupop
    app.kubernetes.io/part-of: brupop
    brupop.bottlerocket.aws/component: agent
  annotations:
    checkov.io/skip1: CKV_K8S_9=readiness not required for agent daemonset
    checkov.io/skip2: CKV_K8S_8=liveness not required for agent daemonset
  name: brupop-agent
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      brupop.bottlerocket.aws/component: agent
  template:
    metadata:
      labels:
        brupop.bottlerocket.aws/component: agent
      namespace: {{ .Values.namespace }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
                  - key: bottlerocket.aws/updater-interface-version
                    operator: In
                    values:
                      - 2.0.0
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - arm64
      containers:
        - command:
            - "./agent"
          env:
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: EXCLUDE_FROM_LB_WAIT_TIME_IN_SEC
              value: "0"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          name: brupop
          resources:
            limits:
              memory: 50Mi
            requests:
              cpu: 10m
              memory: 50Mi
          securityContext:
            seLinuxOptions:
              level: s0
              role: system_r
              type: super_t
              user: system_u
          volumeMounts:
            - mountPath: /run/api.sock
              name: bottlerocket-api-socket
            - mountPath: /bin/apiclient
              name: bottlerocket-apiclient
            - mountPath: /var/run/secrets/tokens/
              name: bottlerocket-agent-service-account-token
            - mountPath: /etc/brupop-tls-keys
              name: bottlerocket-tls-keys
      serviceAccountName: brupop-agent-service-account
      volumes:
        - hostPath:
            path: /run/api.sock
            type: Socket
          name: bottlerocket-api-socket
        - hostPath:
            path: /bin/apiclient
            type: File
          name: bottlerocket-apiclient
        - name: bottlerocket-agent-service-account-token
          projected:
            sources:
              - serviceAccountToken:
                  audience: brupop-apiserver
                  path: bottlerocket-agent-service-account-token
        - name: bottlerocket-tls-keys
          secret:
            optional: false
            secretName: brupop-tls
