apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: brupop-controller
    app.kubernetes.io/managed-by: brupop
    app.kubernetes.io/part-of: brupop
    brupop.bottlerocket.aws/component: brupop-controller
  annotations:
    checkov.io/skip1: CKV_K8S_9=readiness not required for controller deployment
    checkov.io/skip2: CKV_K8S_8=liveness not required for controller
  name: brupop-controller-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCountController }}
  selector:
    matchLabels:
      brupop.bottlerocket.aws/component: brupop-controller
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        brupop.bottlerocket.aws/component: brupop-controller
      namespace: {{ .Values.namespace }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - arm64
      containers:
        - command:
            - "./controller"
          env:
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          name: brupop
      priorityClassName: brupop-controller-high-priority
      serviceAccountName: brupop-controller-service-account
