{{- if .Values.serviceaccountapiserver.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubernetes.io/service-account.name: brupop-apiserver-service-account
  labels:
    app.kubernetes.io/component: apiserver
    app.kubernetes.io/managed-by: brupop
    app.kubernetes.io/part-of: brupop
    brupop.bottlerocket.aws/component: apiserver
  name: {{ .Values.serviceaccountapiserver.name }}
  namespace: {{ .Values.namespace }}
{{- end -}}
