{{- if .Values.servicecontroller.enabled -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: brupop-controller
    app.kubernetes.io/managed-by: brupop
    app.kubernetes.io/part-of: brupop
    brupop.bottlerocket.aws/component: brupop-controller
  name: {{ .Values.servicecontroller.name }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: {{ .Values.servicecontroller.port }}
      targetPort: {{ .Values.servicecontroller.targetPort }}
  selector:
    brupop.bottlerocket.aws/component: brupop-controller
{{- end -}}
