{{- if .Values.serviceaccountcontroller.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubernetes.io/service-account.name: brupop-controller-service-account
  labels:
    app.kubernetes.io/component: brupop-controller
    app.kubernetes.io/managed-by: brupop
    app.kubernetes.io/part-of: brupop
    brupop.bottlerocket.aws/component: brupop-controller
  name: {{ .Values.serviceaccountcontroller.name }}
  namespace: {{ .Values.namespace }}
{{- end -}}
