name: public-helm
on:
  push:
    branches:
      - main

jobs:
  changed-files:
    name: Check for changed files in charts directory
    runs-on: ubuntu-latest
    outputs:
      matrix:  ${{ steps.set-matrix.outputs.matrix }}
      list: ${{ steps.changed-files-specific.outputs.all_changed_files }}
    steps:
      - name: Chekout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get specific changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@v24.1
        with:
          dir_names: true
          files: |
            charts
          json: true
      - name: Debug output
        run: |
          echo ${{ steps.changed-files-specific.outputs.all_changed_files }}
      - id: set-matrix
        run: echo "::set-output name=matrix::{\"chart\":${{ steps.changed-files-specific.outputs.all_changed_files }}}"

  push-charts:
    name: Push Helm Charts if chart root folder
    runs-on: ubuntu-latest
    needs: changed-files
    permissions:
      contents: read
      id-token: write
    if: ${{ needs.changed-files.outputs.list != '[]' && needs.changed-files.outputs.list != '' }}
    strategy:
      matrix: ${{ fromJSON(needs.changed-files.outputs.matrix) }}
    steps:
      - name: Get Chart name
        id: get-chart-name
        env:
          CHANGED_PATH: ${{ matrix.chart }}
        run: |
          CHART_NAME=${CHANGED_PATH//charts\//}
          if [[ "$CHART_NAME" == *\/* ]]
          then
            echo "CHANGES_TO_CHARTS_ROOT_FOLDER=false" >> $GITHUB_ENV
          else
            echo "CHANGES_TO_CHARTS_ROOT_FOLDER=true" >> $GITHUB_ENV
          fi
          echo "CHART_NAME=${CHART_NAME}" >> $GITHUB_ENV
      - name: Chekout
        if: env.CHANGES_TO_CHARTS_ROOT_FOLDER == 'true'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set Env
        if: env.CHANGES_TO_CHARTS_ROOT_FOLDER == 'true'
        run: |
          echo "AWS_REGION=us-east-1" >> "${GITHUB_ENV}"
        shell: bash
      - name: Configure AWS Credentials
        if: env.CHANGES_TO_CHARTS_ROOT_FOLDER == 'true'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions/SPHTech-Platform-helm-chart-bottle-rocket-kaxWaeRe
          role-session-name: gh-actions
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        if: env.CHANGES_TO_CHARTS_ROOT_FOLDER == 'true'
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: public

      - name: Setup Helm
        if: env.CHANGES_TO_CHARTS_ROOT_FOLDER == 'true'
        uses: azure/setup-helm@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Package and push helm chart to Amazon ECR Public
        if: env.CHANGES_TO_CHARTS_ROOT_FOLDER == 'true'
        run: |
          cd ${{ matrix.chart }}
          helm package .
          helm push `ls -Art | tail -n 1` oci://public.ecr.aws/sphmedia/helm/
